#!/usr/bin/env bash
# Hyprland's own example config must not stay in place as the user's
# hyprland.lua: HyDE loads that file last, so the example overrides the theme
# (border colors, animations) and double-binds keys (HyDE-Project/HyDE#2132).

. "$(dirname -- "$0")/lib/common.sh"

# shellcheck source=/dev/null
if ! . "$REPO_ROOT/Scripts/global_fn.sh" 2>/dev/null; then
    fail "unable to source global_fn.sh"
    finish
fi

if ! type retire_autogenerated_hypr_config >/dev/null 2>&1; then
    fail "retire_autogenerated_hypr_config is not defined in global_fn.sh"
    finish
fi

work_dir=$(mktemp -d)
trap 'rm -rf "$work_dir"' EXIT
export cacheDir="$work_dir/cache"

# What Hyprland writes when it starts without a config, as reported in #2132,
# optionally with the loader the v26.8.1 migration prepends.
autogen_body='-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.'
loader='if not hyde then
	dofile(entry)
end
'

case_no=0
# Runs the function on a fresh target; sets $target, $backup and $rc.
run_case() {
    case_no=$((case_no + 1))
    target="$work_dir/$case_no/hypr/hyprland.lua"
    backup="$work_dir/$case_no/state"
    mkdir -p "$(dirname "$target")"
}
# global_fn.sh turns on errexit, so the status is caught, not left to abort.
invoke() {
    rc=0
    retire_autogenerated_hypr_config "$target" "$backup" >/dev/null 2>&1 || rc=$?
}
backups() { find "$backup" -type f -name hyprland.lua 2>/dev/null | wc -l; }

# 1. autogenerated file with the v26.8.1 loader in front: moved aside intact
run_case
printf '%s\n%s\n' "$loader" "$autogen_body" >"$target"
cp "$target" "$work_dir/expected"
invoke
[ "$rc" -eq 0 ] || fail "autogenerated+loader: returned $rc"
[ ! -e "$target" ] || fail "autogenerated+loader: file was left in place"
saved=$(find "$backup" -type f -name hyprland.lua | head -n1)
[ -n "$saved" ] && cmp -s "$saved" "$work_dir/expected" ||
    fail "autogenerated+loader: backup missing or altered"

# 2. autogenerated file on its own (no loader yet)
run_case
printf '%s\n' "$autogen_body" >"$target"
invoke
[ ! -e "$target" ] && [ "$(backups)" -eq 1 ] || fail "autogenerated only: not moved aside"

# 3. HyDE's own template: untouched
run_case
cp "$REPO_ROOT/Configs/.config/hypr/hyprland.lua" "$target"
invoke
[ "$rc" -eq 0 ] && cmp -s "$target" "$REPO_ROOT/Configs/.config/hypr/hyprland.lua" ||
    fail "HyDE template: was changed"
[ "$(backups)" -eq 0 ] || fail "HyDE template: a backup was written"

# 4. the marker text somewhere other than Hyprland's header line: untouched
run_case
printf '%s\n' "$loader" 'hl.bind("F1", hl.dsp.exec_cmd("echo")) -- AUTOGENERATED HYPRLAND CONFIG.' \
    '    -- AUTOGENERATED HYPRLAND CONFIG.' >"$target"
invoke
[ -f "$target" ] && [ "$(backups)" -eq 0 ] || fail "marker mid-line/indented: file was moved"

# 5. no file at all: nothing to do, no backup dir created
run_case
invoke
[ "$rc" -eq 0 ] || fail "missing file: returned $rc"
[ ! -e "$backup" ] || fail "missing file: backup dir created"
[ ! -e "$target" ] || fail "missing file: something was created at the target"

# 6. empty file: untouched
run_case
: >"$target"
invoke
[ "$rc" -eq 0 ] && [ -f "$target" ] && [ "$(backups)" -eq 0 ] || fail "empty file: was touched"

# 7. symlink to an autogenerated file (dotfile manager): link and file untouched
run_case
printf '%s\n' "$autogen_body" >"$work_dir/$case_no/managed.lua"
ln -s "$work_dir/$case_no/managed.lua" "$target"
invoke
[ "$rc" -eq 0 ] && [ -L "$target" ] && [ -f "$work_dir/$case_no/managed.lua" ] ||
    fail "symlink: link or its target was moved"
[ "$(backups)" -eq 0 ] || fail "symlink: a backup was written"

# 8. dangling symlink: left alone, no error
run_case
ln -s "$work_dir/$case_no/nowhere.lua" "$target"
invoke
[ "$rc" -eq 0 ] && [ -L "$target" ] || fail "dangling symlink: not left alone (rc=$rc)"

# 9. a directory where the file should be: untouched
run_case
mkdir "$target"
invoke
[ "$rc" -eq 0 ] && [ -d "$target" ] || fail "directory at target: was touched (rc=$rc)"

# 10. dry run: reported, nothing moved
run_case
printf '%s\n' "$autogen_body" >"$target"
flg_DryRun=1 invoke
[ -f "$target" ] && [ "$(backups)" -eq 0 ] || fail "dry run: file was moved"

# 11. twice in a row (same second): the second backup must not replace the first
run_case
printf '%s\nfirst\n' "$autogen_body" >"$target"
invoke
printf '%s\nsecond\n' "$autogen_body" >"$target"
invoke
[ "$(backups)" -eq 2 ] || fail "repeat run: expected 2 backups, found $(backups)"
grep -rqx first "$backup" && grep -rqx second "$backup" ||
    fail "repeat run: a backup was overwritten"

# 12. backup location unusable: fail, and keep the file where it is
run_case
printf '%s\n' "$autogen_body" >"$target"
: >"$backup" # a file where the backup directory should go
invoke
[ "$rc" -ne 0 ] || fail "unusable backup dir: reported success"
[ -f "$target" ] || fail "unusable backup dir: file was lost"

# 13. the exact header line, but only after the user's own code: untouched
run_case
printf '%s\n' "$loader" 'hl.config({ general = { gaps_in = 2 } })' '' "$autogen_body" >"$target"
invoke
[ -f "$target" ] && [ "$(backups)" -eq 0 ] || fail "header after user code: file was moved"

# 14. with only comments and blank lines before it, Hyprland's header still
# counts; after a leading code line it does not
run_case
printf '%s\n' '-- my notes' '' '-- more notes' "$autogen_body" >"$target"
invoke
[ ! -e "$target" ] || fail "header after leading comments: not moved aside"
run_case
printf '%s\n' 'local x = 1' '-- my notes' "$autogen_body" >"$target"
invoke
[ -f "$target" ] || fail "header after a leading code line: file was moved"

# 15. only the loader's own block is skipped, not any block ending in 'end'
run_case
printf '%s\n' 'if other then' 'end' "$autogen_body" >"$target"
invoke
[ -f "$target" ] || fail "header after a non-loader block: file was moved"

# Restore: puts the retired file back only when the deploy left nothing there.
restore() {
    rc=0
    restore_retired_hypr_config "$target" >/dev/null 2>&1 || rc=$?
}

# 16. deploy did not replace it: the retired file goes back, content intact
run_case
printf '%s\n%s\n' "$loader" "$autogen_body" >"$target"
cp "$target" "$work_dir/expected"
invoke
restore
[ "$rc" -eq 0 ] && cmp -s "$target" "$work_dir/expected" ||
    fail "restore after failed deploy: file not put back (rc=$rc)"

# 17. deploy put the template in place: left as is, backup kept
run_case
printf '%s\n' "$autogen_body" >"$target"
invoke
printf 'template\n' >"$target"
restore
[ "$rc" -eq 0 ] && [ "$(cat "$target")" = template ] && [ "$(backups)" -eq 1 ] ||
    fail "restore after successful deploy: template or backup touched"

# 18. a later run that retired nothing resets the record: a missing target
# stays missing instead of getting an older run's file
run_case
printf '%s\n' "$autogen_body" >"$target"
invoke
run_case
printf 'plain\n' >"$target"
invoke
rm -f "$target"
restore
[ "$rc" -eq 0 ] && [ ! -e "$target" ] || fail "restore without a retire: something was put back"

# 19. a dry run records nothing to restore
run_case
printf '%s\n' "$autogen_body" >"$target"
flg_DryRun=1 invoke
restore
[ "$rc" -eq 0 ] && [ -f "$target" ] || fail "restore after dry run: target changed"

finish
